### ISSUE TITLE
unable to import Model

### ISSUE THREAD

**Issue by michaelneale** [cloudwalkio/omg-monitor#35]
Trying with the latest - saw this (also with run_monitor.py as well as run_monitor_dyn.py) - looks like something has moved around again? 

root@49f7931c0f23:/home/docker/omg-monitor# tail -f /var/log/docker/monitor/processes_error.log
    from monitor import Monitor
  File "/home/docker/omg-monitor/monitor/monitor.py", line 4, in <module>
    from nupic.frameworks.opf.modelfactory import ModelFactory
ImportError: No module named nupic.frameworks.opf.modelfactory
Traceback (most recent call last):
  File "run_monitor_dyn.py", line 4, in <module>
    from monitor import Monitor
  File "/home/docker/omg-monitor/monitor/monitor.py", line 4, in <module>
    from nupic.frameworks.opf.modelfactory import ModelFactory
ImportError: No module named nupic.frameworks.opf.modelfactory

**Comment by michaelneale** [comment]
Actually - I upgraded to latest image - and it seems ok now... probably was old cached version of it. Had to blow away my boot2docker setup for this ;)
